### ISSUE TITLE
I found some problem

### ISSUE THREAD

**Issue by huiyadanli** [DotSaikyo/Live2D#1]
1. in `assets/asuna/22.sao` & `assets/asuna/22.alo`
    line 3  `"physics":"22/physics.json"`  
    missing a comma at the end of line.
    because of it, I can not see all asuna models by using change model function.

2. refresh the page when the `#btnHidebtn` was unchecked, the `#btnHidebtn` is unchecked and the `#hide` hide .
    the `#btnHidebtn` change event should be call when page onload.

**Comment by KasaiDot** [comment]
Thnx for the report !
I'm currently into modifying the JS files.
It should be okay soon, if it not this night (GMT+1), test it tomorow, GitHub should have a new commit.

If you want to help into modifying the page, do not hesit ;D

**Comment by KasaiDot** [comment]
Will be in late for the update, ~sorry.

**Comment by huiyadanli** [comment]
Don't mind it :smile:

**Comment by KasaiDot** [comment]
Hi, new commit sent!
Check it out: d772b97

**Comment by KasaiDot** [comment]
Issue cleared with the pull #2
