### ISSUE TITLE
Limited Selection Area | #3

### ISSUE THREAD

**Issue by KasaiDot** [DotSaikyo/Live2D#12]
Reference the #3 issue

Right now the models can only be manipulated by a selected area (canvas), but in the version of @avgjs of the pixi-live2d project
Like i already said in the #3 issue, since the documentation is not well documented, we have to work on it with/without it.

**Comment by Icemic** [comment]
Hi, I am the maintainer of pixi-live2d.

However, I haven't fully understood what you mean. Do you mean there are some bugs in pixi-live2d?

If so, please give me more details and I'll try to fix it soon.

**Comment by huiyadanli** [comment]
@Icemic My understanding was that the mouse event (to control model's head) is on the cavans in [his project](https://github.com/DotSaikyo/Live2D), but in [your project demo](https://avgjs.github.io/pixi-live2d-example/), the mouse event is on the window.

@KasaiDot  Maybe I understand what you said.

In [SampleApp1.js](https://github.com/DotSaikyo/Live2D/blob/master/static/js/live2d/SampleApp1.js),

```javascript
function initL2dCanvas(canvasId)
{
    
    this.canvas = document.getElementById(canvasId);
    
    
    if(this.canvas.addEventListener) {
        this.canvas.addEventListener("mousewheel", mouseEvent, false);
        this.canvas.addEventListener("click", mouseEvent, false);
        this.canvas.addEventListener("mousedown", mouseEvent, false);
        this.canvas.addEventListener("mousemove", mouseEvent, false);
        this.canvas.addEventListener("mouseup", mouseEvent, false);
        this.canvas.addEventListener("mouseout", mouseEvent, false);
        this.canvas.addEventListener("contextmenu", mouseEvent, false);
        this.canvas.addEventListener("touchstart", touchEvent, false);
        this.canvas.addEventListener("touchend", touchEvent, false);
        this.canvas.addEventListener("touchmove", touchEvent, false);
    }
    
    btnChangeModel = document.getElementById("btnChange");
    btnChangeModel.addEventListener("click", function(e) {
        changeModel();
    });
}
```

replace `this.canvas` with `window`.

```javascript
function initL2dCanvas(canvasId)
{
    
    //this.canvas = document.getElementById(canvasId);
    
    
    if(this.canvas.addEventListener) {
        window.addEventListener("mousewheel", mouseEvent, false);
        window.addEventListener("click", mouseEvent, false);
        window.addEventListener("mousedown", mouseEvent, false);
        window.addEventListener("mousemove", mouseEvent, false);
        window.addEventListener("mouseup", mouseEvent, false);
        window.addEventListener("mouseout", mouseEvent, false);
        window.addEventListener("contextmenu", mouseEvent, false);
        window.addEventListener("touchstart", touchEvent, false);
        window.addEventListener("touchend", touchEvent, false);
        window.addEventListener("touchmove", touchEvent, false);
    }
    
    btnChangeModel = document.getElementById("btnChange");
    btnChangeModel.addEventListener("click", function(e) {
        changeModel();
    });
}
```

Try it.

**Comment by Icemic** [comment]
Oh, I get it.

All event listening in pixi-live2d is implemented by pixi.js, in other words, pixi.js attach `mousemove` to `window`.

To limit it in the canvas, just set `renderer.plugins.interation.moveWhenInside=true`

Put it after `const renderer = new PIXI.WebGLRenderer(800, 600);` if you use my example.

Referace:
https://github.com/pixijs/pixi.js/issues/2310
http://pixijs.download/release/docs/PIXI.interaction.InteractionManager.html

**Comment by KasaiDot** [comment]
@huiyadanli thnx for the help i'll test it tonight.
I never had the time to take a look in the files but with the code presented I think it'll maybe work.

@Icemic no you are misunderstood my message, I never said your project had bugs (hopefully I didn't) I just said that the things you discribe like a "documentation" is not fully understandable (witch mean I didn't understand it well) I'll already try to make the "demo" with the code you provide in the "demo-pixi-live2d" project but it didn't work, since it require many files outside the demo folder, if I had time one day, I'll watch a bit longer your code for fully understand it.
Anyway thnx for your help.

**Comment by KasaiDot** [comment]
@huiyadanli bug fixed in the 1488a7d commit & the #11 PR
You can add modifications if you want.
Thnx for the report.

**Comment by KasaiDot** [comment]
@Icemic can you do a exemple please?
push your work in the pixi branch please.

**Comment by Icemic** [comment]
Done. #13
